const acceptOfferTypes = {
  PUT_ACCEPT_OFFER_SUCCESS: 'PUT_ACCEPT_OFFER_SUCCESS',
  PUT_ACCEPT_OFFER_FAILURE: 'PUT_ACCEPT_OFFER_FAILURE',
  PUT_ACCEPT_OFFER_PENDING: 'PUT_ACCEPT_OFFER_PENDING',
};

export default acceptOfferTypes;
