const cancelOfferTypes = {
  DELETE_CANCEL_OFFER_SUCCESS: 'DELETE_CANCEL_OFFER_SUCCESS',
  DELETE_CANCEL_OFFER_FAILURE: 'DELETE_CANCEL_OFFER_FAILURE',
  DELETE_CANCEL_OFFER_PENDING: 'DELETE_CANCEL_OFFER_PENDING',
};

export default cancelOfferTypes;
