const categoryTypes = {
  FETCH_CATEGORY_PENDING: 'FETCH_CATEGORY_PENDING',
  FETCH_CATEGORY_SUCCESS: 'FETCH_CATEGORY_SUCCESS',
  FETCH_CATEGORY_FAILURE: 'FETCH_CATEGORY_FAILURE',
};

export default categoryTypes;
