const createProductTypes = {
  POST_CREATE_PRODUCT_PENDING: 'POST_CREATE_PRODUCT_PENDING',
  POST_CREATE_PRODUCT_SUCCESS: 'POST_CREATE_PRODUCT_SUCCESS',
  POST_CREATE_PRODUCT_FAILURE: 'POST_CREATE_PRODUCT_FAILURE',
  POST_CREATE_PRODUCT_RESET: 'POST_CREATE_PRODUCT_RESET',
};

export default createProductTypes;
