const givenOffersTypes = {
  FETCH_GIVEN_OFFERS_PENDING: 'FETCH_GIVEN_OFFERS_PENDING',
  FETCH_GIVEN_OFFERS_SUCCESS: 'FETCH_GIVEN_OFFERS_SUCCESS',
  FETCH_GIVEN_OFFERS_FAILURE: 'FETCH_GIVEN_OFFERS_FAILURE',
};

export default givenOffersTypes;
