const productDetailTypes = {
  FETCH_PRODUCT_DETAIL_PENDING: 'FETCH_PRODUCT_DETAIL_PENDING',
  FETCH_PRODUCT_DETAIL_SUCCESS: 'FETCH_PRODUCT_DETAIL_SUCCESS',
  FETCH_PRODUCT_DETAIL_FAILURE: 'FETCH_PRODUCT_DETAIL_FAILURE',
};

export default productDetailTypes;
