const purchaseTypes = {
  PUT_PURCHASE_PENDING: 'PUT_PURCHASE_PENDING',
  PUT_PURCHASE_SUCCESS: 'PUT_PURCHASE_SUCCESS',
  PUT_PURCHASE_FAILURE: 'PUT_PURCHASE_FAILURE',
};

export default purchaseTypes;
