const receivedOffersTypes = {
  FETCH_RECEIVED_OFFERS_PENDING: 'FETCH_RECEIVED_OFFERS_PENDING',
  FETCH_RECEIVED_OFFERS_SUCCESS: 'FETCH_RECEIVED_OFFERS_SUCCESS',
  FETCH_RECEIVED_OFFERS_FAILURE: 'FETCH_RECEIVED_OFFERS_FAILURE',
};

export default receivedOffersTypes;
