const rejectOfferTypes = {
  POST_REJECT_OFFER_PENDING: 'POST_REJECT_OFFER_PENDING',
  POST_REJECT_OFFER_SUCCESS: 'POST_REJECT_OFFER_SUCCESS',
  POST_REJECT_OFFER_FAILURE: 'POST_REJECT_OFFER_FAILURE',
};

export default rejectOfferTypes;
