const uploadTypes = {
  POST_UPLOAD_PENDING: 'POST_UPLOAD_PENDING',
  POST_UPLOAD_SUCCESS: 'POST_UPLOAD_SUCCESS',
  POST_UPLOAD_FAILURE: 'POST_UPLOAD_FAILURE',
  POST_UPLOAD_RESET: 'POST_UPLOAD_RESET',
};

export default uploadTypes;
